server.port: 8091
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

spring:
  profiles:
    active: local
---
spring:
  profiles:
  - local
  datasource:
    url: jdbc:postgresql://localhost:5431/base_a
    username: postgres
    password: example
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
---
spring:
  profiles:
  - container
  datasource:
    url: jdbc:postgresql://base_b_db:5432/base_a
    username: postgres
    password: example
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
---
spring:
  profiles:
  - aws
  datasource:
    url: jdbc:postgresql://prova-db.c1u3yzfg4dgd.sa-east-1.rds.amazonaws.com:5432/base_b?ssl=true
    username: postgres
    password: gr3m1oc4mpea0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
