version: '3.1'

services:

  base_b_db:
    image: base-a-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5431:5432

  app_b:
    image: app_b
    restart: always
    depends_on:
      - base_b_db
    ports:
      - 8091:8091

